### ISSUE TITLE
Add rss feed recommendation

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/reading-documentation-and-newsletters#2]
Recommend clients like https://netnewswire.com/

**Comment by heratyian** [comment]
Can recommend subscribing to news.dpi.dev rss feed.

**Comment by heratyian** [comment]
Any @DPI-WE/teaching-assistants have bandwidth for this?

**Comment by ajmompr** [comment]
> Any @DPI-WE/teaching-assistants have bandwidth for this?

@heratyian I can work on this!
